name: Checker Script CI

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Rust environment (required for cargo stylus commands)
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Step 3: Install cargo-stylus
      - name: Install cargo-stylus
        run: |
          cargo install cargo-stylus

      # Step 4: Make checker.sh executable
      - name: Make checker.sh executable
        run: chmod +x ./checker.sh

      # Step 5: Run the checker.sh script (it will fetch the latest SDK version)
      - name: Run checker script
        run: ./checker.sh

      # Optionally: Check for issues in the log
      - name: Check for issues in the log
        if: success()
        run: |
          if grep -q "FAILED" check_results.log; then
            echo "Checker script failed! Fix the issues before merging."
            exit 1
          else
            echo "Checker script passed! Ready to merge."
          fi
