name: Scheduled SDK Bump

on:
  schedule:
    - cron: '0 2 * * 0'      # every Sunday at 02:00 UTC
  push:
    branches:
      - master
    tags-ignore:
      - 'chore/sdk-bump-*'

jobs:
  bump-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq & curl
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - id: get_version
        run: |
          version=$(curl -s https://crates.io/api/v1/crates/stylus-sdk \
                     | jq -r '.crate.max_version')
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Make checker.sh executable
        run: chmod +x ./checker.sh

      - name: Bump to latest SDK & run checks
        run: ./checker.sh -v ${{ steps.get_version.outputs.VERSION }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: chore/sdk-bump-${{ steps.get_version.outputs.VERSION }}
          title: >
            chore: bump stylus-sdk -> ${{ steps.get_version.outputs.VERSION }}
          body: |
            This PR updates all example `Cargo.toml` files to `stylus-sdk` v${{ steps.get_version.outputs.VERSION }}
            and verifies that `cargo stylus check` and `export-abi` still pass.
          labels: |
            chore
            dependencies
